[package]
name = "aurion"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
cpal = "0.16.0"
crossbeam-channel = "0.5.15"
crossbeam = "0.8.4"
pollster = "0.4.0"
rustfft = "6.4.1"
thiserror = "2.0.17"
wgpu = "26.0.1"
winit = "0.30.12"
